volumes:
  postgres_volume:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  pvz-network:
    driver: bridge

services:
  pvz-service:
    build: .
    container_name: pvz-service
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - PG_HOST=pvz-db
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE_NAME=${PG_DATABASE_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=:8080
    depends_on:
      pvz-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pvz-network

  pvz-db:
    image: postgres:14-alpine3.19
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pvz_user -d pvz_dev -h localhost -p 5432 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - pvz-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    depends_on:
      pvz-db:
        condition: service_healthy
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE_NAME=${PG_DATABASE_NAME}
    volumes:
      - ./migrations:/root/migrations
    networks:
      - pvz-network

  redis:
    image: redis:7.0-alpine
    container_name: PvzRedis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - pvz-network

  prometheus:
    image: prom/prometheus:v2.45.6
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    networks:
      - pvz-network

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - pvz-network