server:
  port: ":8080"

database:
  host: "localhost"
  port: "5432"
  user: "pvz_user"
  password: "pvz_pass"
  name: "pvz_dev"

redis:
  host: localhost
  port: "6379"
  password: ""
  db: 0

jwt:
  secret_key: "super-secret-key-for-local"
  expiration: "24h"
