server:
  port: ":8080"

database:
  host: "pvz-db"
  port: "5432"
  user: "pvz_user"
  password: "pvz_pass"
  name: "pvz_dev"

redis:
  host: redis
  port: "6379"
  password: ""
  db: 0

jwt:
  secret_key: "super-secret-key-for-local"
  expiration: "24h"

kafka:
  brokers:
    - "kafka:9092"
  topic: "pvz-events"