server:
  port: ":80"

database:
  host: pvz-postgres.prod.internal
  port: "5432"
  user: pvz_user
  password: strong-password-in-prod
  name: pvz_prod

redis:
  host: pvz-redis.prod.internal
  port: "6379"
  password: redis-strong-pass
  db: 0

jwt:
  secret_key: very-very-secret-key-change-in-real-prod
  expiration: "2h"